# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
